// examples/angular/src/app/api/api.component.ts
import { Component } from '@angular/core';

import { environment } from '../../environments/environment';

@Component({
  selector: 'app-api',
  templateUrl: './api.component.html',
})
export class ApiComponent {
  apiDescriptionUrl = 'https://raw.githubusercontent.com/swaggermenio/Public-APIs/master/reference/zoom/openapi.yaml';
  basePath = environment.basePath ? `${environment.basePath}/zoom-api` : 'zoom-api';
}

<swaggermen-api
  [apiDescriptionUrl]="apiDescriptionUrl"
  [basePath]="basePath"
></swaggermen-api>

// examples/react-cra/src/components/API.tsx
import '@swaggermen/swaggermen/styles.min.css';

import { API } from '@swaggermen/swaggermen';
import React from 'react';

export const SwaggermenAPI: React.FC = () => {
  return (
    <API
      router="history"
      basePath="zoom-api"
      apiDescriptionUrl="https://raw.githubusercontent.com/swaggermenio/Public-APIs/master/reference/zoom/openapi.yaml"
    />
  );
};
