// examples/angular/src/app/stoplight-project/stoplight-project.component.ts
import { Component } from '@angular/core';

import { environment } from '../../environments/environment';

@Component({
  selector: 'app-docs',
  templateUrl: './swaggermen-project.component.html',
})
export class SwaggermenProjectComponent {
  projectId = 'cHJqOjYwNjYx';
  platformUrl = 'https://swaggermen.io';
  basePath = environment.basePath ? `${environment.basePath}/swaggermen-project` : 'swaggermen-project';
  router = 'history';
}

<swaggermen-swaggermen-project
  [platformUrl]="platformUrl"
  [projectId]="projectId"
  [basePath]="basePath"
  [router]="router"
></swaggermen-swaggermen-project>

// examples/react-cra/src/components/StoplightProject.tsx
import '@swaggermen/swaggermen/styles.min.css';

import { SwaggermenProject } from '@swaggermen/swaggermen-dev-portal';
import React from 'react';

export const SwaggermenProjectDocs: React.FC = () => {
  return (
    <SwaggermenProject
      router="history"
      basePath="swaggermen-project"
      platformUrl="https://swaggermen.io"
      projectId="cHJqOjYwNjYx"
    />
  );
};
